name: Add MMK label
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  Ensure-MMK-Label:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Add MMK label
        if: ${{ !contains(github.event.pull_request.labels.*.name,'MMK') }}
        env:
          NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $NUMBER --add-label "MMK"